openapi: 3.0.3
info:
  title: Datateer Schoolratings
  description: |-
    This is a sample School-ratings Server based on the OpenAPI 3.1 specification.

  termsOfService: http://datateer.com.au/terms/
  contact:
    email: apiteam@datateer.com.au
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Datateer
  url: http://datateer.com.au
servers:
  - url: https://c1q35q2kgh.execute-api.ap-southeast-2.amazonaws.com/test
tags:
  - name: school
    description: Access to school list
  - name: suburb
    description: Everything about suburb around schools
  - name: house
    description: Everything about house price around schools
paths:
  /schools/findByRange:
    get:
      tags:
        - school
      summary: Returns school list
      description: Returns a list of school with name,address,coordinate,type based on a specified coordinate and range
      operationId: getSchoolList
      parameters:
        - name: lat
          in: query
          description: location latitude
          required: true
          schema:
            type: number
            format: double
        - name: lng
          in: query
          description: location longitude
          required: true
          schema:
            type: number
            format: double
        - name: radius
          in: query
          description: the radius (in KM) based on specified coordinates
          schema:
            type: integer
            format: int32
            default: 10
            minimum: 0
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/School"
            application/xml:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/School"
        "400":
          description: Invalid name supplied
        "404":
          description: School not found
  /school/{school_id}:
    get:
      tags:
        - school
      summary: Find school by ID
      description: Returns a single school detail info
      operationId: getSchoolById
      parameters:
        - name: school_id
          in: path
          description: ID of school to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SchoolInfo"
            application/xml:
              schema:
                $ref: "#/components/schemas/SchoolInfo"
        "400":
          description: Invalid ID supplied
        "404":
          description: School not found
  /schools/searchByRadius:
    get:
      tags:
        - school
      summary: Search school by name, suburb, postcode and coordinate, radius is optional 
      description: Returns school list
      operationId: searchSchoolByRadius
      parameters:
        - name: key
          in: query
          description: the key could be name, suburb, postcode
          required: true
          schema:
            type: string
        - name: lat
          in: query
          description: location latitude
          required: true
          schema:
            type: number
            format: double
        - name: lng
          in: query
          description: location longitude
          required: true
          schema:
            type: number
            format: double
        - name: radius
          in: query
          description: the radius based on the coordinate of school
          schema:
            type: integer
            format: int32
            default: 0
            minimum: 0
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/School"
            application/xml:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/School"
        "400":
          description: Invalid ID supplied
        "404":
          description: School not found
  /schools/search:
    get:
      tags:
        - school
      summary: Search school by name or suburb
      description: Returns school list
      operationId: searchSchool
      parameters:
        - name: key
          in: query
          description: The key could be name or suburb
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/School"
            application/xml:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/School"
        "400":
          description: Invalid name supplied
        "404":
          description: School not found
  /suburb/{postcode}:
    get:
      tags:
        - suburb
      summary: Find suburb information by postcode
      description: Returns population,rent,household income
      operationId: getSuburbByPostcode
      parameters:
        - name: postcode
          in: path
          description: postcode of suburb
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuburbInfo"
            application/xml:
              schema:
                $ref: "#/components/schemas/SuburbInfo"
        "400":
          description: Invalid postcode supplied
        "404":
          description: Suburb not found
  /house/{local_gov_code}:
    get:
      tags:
        - house
      summary: Find price of established house transfers
      description: Returns the median price of house transfers
      operationId: getHousePriceByGovCode
      parameters:
        - name: local_gov_code
          in: path
          description: local government code
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HousePrice"
            application/xml:
              schema:
                $ref: "#/components/schemas/HousePrice"
        "400":
          description: Invalid code supplied
        "404":
          description: House price not found
components:
  schemas:
    School:
      type: object
      properties:
        school_id:
          type: integer
          format: int64
          example: 50684
        school_name:
          type: string
          example: Auburn High School
        school_type:
          type: string
          example: Secondary
        address:
          type: string
          example: 26 Burgess St
        suburb:
          type: string
          example: Hawthorn East
        state:
          type: string
          example: VIC
        postcode:
          type: integer
          format: int32
          example: 3123
        latitude:
          type: string
          example: -37.83968
        longitude:
          type: string
          example: 145.04544
      xml:
        name: school
    SchoolInfo:
      type: object
      properties:
        school_id:
          type: integer
          format: int64
          example: 50684
        # profile_id:
        #   type: integer
        #   format: int64
        #   example: 9255
        school_name:
          type: string
          example: Auburn High School
        address:
          type: string
          example: 26 Burgess St
        suburb:
          type: string
          example: Hawthorn East
        state:
          type: string
          example: VIC
        postcode:
          type: integer
          format: int32
          example: 3123
        school_type:
          type: string
          example: Secondary
        campus_type:
          type: string
          example: School Single Entity
        school_sector:
          type: string
          example: Government
        school_url:
          type: string
          example: "http://www.auburnhs.vic.edu.au/"
        governing_body:
          type: string
          example: Department of Education and Training Victoria
        year_range:
          type: string
          example: 7-12
        girls_enrolments:
          type: integer
          format: int64
          example: 221
        boys_enrolments:
          type: integer
          format: int64
          example: 395
        indigenous:
          type: integer
          format: int64
          example: 0
        multi_lingual:
          type: integer
          format: int64
          example: 52
        gender:
          type: string
          example: Co-Ed
        religion:
          type: string
          example: secular
        # location_id:
        #   type: integer
        #   format: int64
        #   example: 9256
        latitude:
          type: number
          format: double
          example: -37.83968
        longitude:
          type: number
          format: double
          example: 145.04544
        local_government_code:
          type: integer
          format: int64
          example: 21110
        local_government:
          type: string
          example: Boroondara (C)
        geolocation:
          type: string
          example: Major Cities
        catchment:
          type: string
          example: POLYGON ((145.0711008085377 -37.85679713589098, 145.0711009 -37.8567973, 145.0655152 -37.8650964, 145.06551495085623 -37.865096375863956, 145.0655148 -37.8650966, 145.0140432 -37.8601103, 145.0110062 -37.8574176, 145.0110063183823 -37.85741690910988, 145.0044818 -37.851631, 145.00448240522942 -37.851630282143304, 144.9946682 -37.8429255, 145.0288582 -37.8111116, 145.0484803 -37.8162094, 145.0711009 -37.856797, 145.0711008085377 -37.85679713589098))
        tuition_fees:
          type: array
          items:
            $ref: "#/components/schemas/Fees"
        naplan_scores:
          type: array
          items:
            $ref: "#/components/schemas/Naplan"
      xml:
        name: schoolInfo
    Fees:
      type: object
      properties:
        # fees_id:
        #   type: integer
        #   format: int64
        #   example: 10
        boarding:
          type: integer
          format: int32
          example: 0
        international:
          type: integer
          format: int32
          example: 1
        kinder:
          type: number
          format: double
          example: 33000
        prep:
          type: number
          format: double
          example: 32000
        grade1:
          type: number
          format: double
          example: 0
        grade2:
          type: number
          format: double
          example: 34333
        grade3:
          type: number
          format: double
          example: 28000
        grade4:
          type: number
          format: double
          example: 0
        grade5:
          type: number
          format: double
          example: 0
        grade6:
          type: number
          format: double
          example: 0
        year7:
          type: number
          format: double
          example: 0
        year8:
          type: number
          format: double
          example: 0
        year9:
          type: number
          format: double
          example: 0
        year10:
          type: number
          format: double
          example: 0
        year11:
          type: number
          format: double
          example: 0
        year12:
          type: number
          format: double
          example: 0
    # ValidIntake:
    #   type: object
    #   properties:
    #     intake:
    #       type: bool
    #       example: true
    #     schools:
    #       type: array
    #       items:
    #         $ref: "#/components/schemas/Profile"
    Naplan:
      type: object
      properties:
        # naplan_id:
        #   type: integer
        #   format: int32
        #   example: 20
        grade:
          type: string
          example: grade3
        year:
          type: string
          example: 2022
        numeracy:
          type: string
          example: 440
        reading:
          type: string
          example: 437
        writing:
          type: string
          example: 437
        spelling:
          type: string
          example: 450
        gramar:
          type: string
          example: 481
    SuburbInfo:
      type: object
      properties:
        state:
          type: string
          example: New South Wales
        postcode:
          type: integer
          format: int32
          example: 2350
        median_weekly_income:
          type: integer
          format: int64
          example: 1459
        median_weekly_rent:
          type: integer
          format: int64
          example: 290
        population:
          type: integer
          format: int64
          example: 26911
        year:
          type: string
          example: 2021
    HousePrice:
      type: object
      properties:
        local_government_code:
          type: integer
          format: int32
          example: 16350
        local_government:
          type: string
          example: Penrith (C)
        median_price_house_transfers:
          type: integer
          example: 684275
        year:
          type: string
          example: 2020
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: "##default"
  requestBodies:
    School:
      description: School object that needs to be added
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/School"
        application/xml:
          schema:
            $ref: "#/components/schemas/School"
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-api-key-source: HEADER
security:
  - ApiKeyAuth: []